#!/bin/sh

bspc config border_width         5
bspc config normal_border_color  \#2E3440
bspc config active_border_color  \#2E3440
bspc config focused_border_color \#3B4252
bspc config window_gap           30
