#!/bin/bash

DIR=`dirname $(readlink -f $0)`

# ---
# Displays the command help and an error message, if present.
#
# @param $1 An error message.
# ---
function help() {
    if [ "$*" != "" ] ; then
        echo -e "\E[31;7m$*\033[0m"
    fi

cat << EOF
Usage: themer [OPTION] THEME
Changes the wallpaper and current theme for bspwm, polybar and more.

Options:
  -c, --colors  The colors to use.
  -h, --help    Display this help and exit
  -l, --list    Display the list of available themes
  -r, --random  Applies a random theme
  -t, --theme   The theme to configure
EOF

    if [ "$*" != "" ] ; then
        exit 1
    fi

    exit 0
}

# ---
# Displays a list of available themes
# ---
function list() {
    local themes=$(ls $DIR/themes | tr "\n" " ")
    local colors=$(ls $DIR/colors | sed -e "s/\.sh//g"  | tr "\n" " ")

    echo -e "Themes\n   $themes"
    echo -e "Colors\n   $colors"

    exit 0
}

# ---
# Changes the current theme.
# ---
function main() {
    local colors=$(cat $HOME/.themer.conf | grep colors | sed -e "s/colors\s*=\s*//")
    local theme=$(cat $HOME/.themer.conf | grep theme | sed -e "s/theme\s*=\s*//")

    while [[ $# -gt 0 ]]; do
        case "$1" in
            -h | --help )
                help ;;

            -c | --colors )
                colors=$2
                shift
                ;;

            -l | --list )
                list
                ;;

            -r | --random )
                theme=$(randomTheme)
                colors=$(randomColors)
                ;;

            -t | --theme )
                theme=$2
                shift
                ;;

            * )
                help "Unknown option '$1'"
                ;;
        esac

        shift;
    done

    # No theme to apply
    if [[ ! $theme ]] || [[ ! -d $DIR/themes/$theme ]]; then
        help "Unknown theme \"$theme\""
    fi

    if [ ! -f $DIR/colors/$colors.sh ]; then
        help "Unknown color scheme \"$colors\""
    fi

    echo "theme = $theme" > $HOME/.themer.conf
    echo "colors = $colors" >> $HOME/.themer.conf

    selectWallpaper $colors

    echo "Applying $theme theme with $colors colors..."

    source $DIR/colors/$colors.sh

    updateDunst     $theme
    updateKitty     $theme
    updateWaybar    $theme
    updateRofi      $theme
    updateYazi      $theme
    updateZsh       $theme
    updateTmux      $theme
    updateVim
    updateHyprland  $theme
    updateWallpaper $theme $colors
}

# ---
# Returns a random color scheme.
# ---
function randomColors() {
    colors=$(ls $DIR/colors | sed -e "s/\.sh//g")
    size=$(echo "$colors" | wc -w)

    i=0
    array=()
    for c in $colors; do
        array[$i]="$c"
        i=$(($i+1))
    done

    color=$(($RANDOM % $size))

    echo ${array[$color]}
}

# ---
# Returns a random theme.
# ---
function randomTheme() {
    themes=$(ls $DIR/themes)
    size=$(echo "$themes" | wc -w)

    i=0
    array=()
    for t in $themes; do
        array[$i]="$t"
        i=$(($i+1))
    done

    theme=$(($RANDOM % $size))

    echo ${array[$theme]}
}

# ---
# Selects the wallpaper based on colors.
#
# @param $1 The colors.
# ---
function selectWallpaper() {
    WALLPAPER=`ls $DIR/wallpapers/$1 | grep ".*\.\(png\|jpg\)"`
    ARGS=''
    LOCK=''
    i=0

    for w in $WALLPAPER; do
        ARGS="$DIR/wallpapers/$1/$w"

        if [ $i -eq 0 ]; then
            LOCK="$DIR/wallpapers/$1/$w"
        fi

        i=$(($i+1))
    done

    export wallpaper="$ARGS"
}

# ---
# Updates the dunst configuration.
#
# @param $1 The theme name.
# ---
function updateDunst() {
    command -v dunstify > /dev/null 2>&1 || return

    echo -en "  Changing dunst theme........................"

    [ -f $HOME/.config/dunst/dunstrc ] && rm $HOME/.config/dunst/dunstrc

    if  [[ ! -f $DIR/themes/$1/dunst/dunstrc ]]; then
        echo -e "\E[1;33mSKIP\033[0m"
        return
    fi

    mkdir -p $HOME/.config/dunst
    envsubst < $DIR/themes/$1/dunst/dunstrc > $HOME/.config/dunst/dunstrc
    killall dunst > /dev/null 2>&1

    echo -e "\E[1;32mDONE\033[0m"
}

# ---
# Changes the hyprland theme.
#
# @param $1 The theme name.
# ---
function updateHyprland() {
    command -v hyprctl > /dev/null 2>&1 || return

    echo -en "  Changing hyprland theme....................."

    if [[ ! -f $DIR/themes/$1/hypr/theme.conf ]]; then
        echo -e "\E[1;33mSKIP\033[0m"
        return
    fi

    mkdir -p $HOME/.config/hypr
    envsubst < $DIR/themes/$1/hypr/theme.conf > $HOME/.config/hypr/theme.conf

    hyprctl reload > /dev/null

    echo -e "\E[1;32mDONE\033[0m"
}

# ---
# Changes the kitty theme.
#
# @param $1 The theme name.
# ---
function updateKitty() {
    command -v kitty > /dev/null 2>&1 || return

    echo -en "  Changing kitty theme........................"

    [ -f $HOME/.config/kitty/kitty.conf ] && rm $HOME/.config/kitty/kitty.conf

    if [[ ! -f $DIR/themes/$1/kitty/kitty.conf ]]; then
        echo -e "\E[1;33mSKIP\033[0m"
        return
    fi

    mkdir -p $HOME/.config/kitty
    envsubst < $DIR/themes/$1/kitty/kitty.conf > $HOME/.config/kitty/kitty.conf

    if [[ -x `command -v wdotool` ]]; then
        wdotool key 'ctrl+shift+F5' > /dev/null 2>&1
    fi

    echo -e "\E[1;32mDONE\033[0m"
}

# ---
# Changes the rofi theme.
#
# @param $1 The theme name.
# ---
function updateRofi() {
    command -v rofi > /dev/null 2>&1 || return

    echo -en "  Changing rofi theme........................."

    mkdir -p $HOME/.config/rofi

    for file in $(ls $DIR/themes/$1/rofi); do
        [ -f $HOME/.config/rofi/$file ] && rm $HOME/.config/rofi/$file

        envsubst < $DIR/themes/$1/rofi/$file > $HOME/.config/rofi/$file
    done

    echo -e "\E[1;32mDONE\033[0m"
}

# ---
# Changes the tmux theme.
#
# @param $1 The theme name.
# ---
function updateTmux() {
    command -v tmux > /dev/null 2>&1 || return

    echo -en "  Changing tmux theme........................."

    [ -f $HOME/.config/tmux/theme.conf ] && rm $HOME/.config/tmux/theme.conf

    if [[ ! -f $DIR/themes/$1/tmux/theme.conf ]]; then
        echo -e "\E[1;33mSKIP\033[0m"
        return
    fi

    mkdir -p $HOME/.config/tmux
    envsubst < $DIR/themes/$1/tmux/theme.conf > $HOME/.config/tmux/theme.conf

    if [[ `ps aux | grep tmux | tail -n +2` ]]; then
        tmux source-file $HOME/.config/tmux/theme.conf
    fi

    echo -e "\E[1;32mDONE\033[0m"
}

# ---
# Changes the vim colorschemes.
# ---
function updateVim() {
    if [[ ! -x `command -v vim` ]] && [[ ! -x `command -v nvim` ]]; then
        return
    fi

    echo -en "  Changing vim theme.........................."

    mkdir -p $HOME/.config/nvim/lua/colors
    envsubst < $DIR/templates/vim/colors.lua > $HOME/.config/nvim/lua/theme/colors.lua

    echo -e "\E[1;32mDONE\033[0m"
}

# ---
# Changes the current wallpaper.
#
# @param $1 The theme name.
# @param $2 The color name
# ---
function updateWallpaper() {
    echo -en "  Changing wallpaper.........................."

    envsubst < $DIR/themes/$1/hypr/hyprpaper.conf > $HOME/.config/hypr/hyprpaper.conf
    killall hyprpaper > /dev/null 2>&1
    hyprpaper > /dev/null 2>&1 &

    echo -e "\E[1;32mDONE\033[0m"
}

# ---
# Changes the waybar theme.
#
# @param $1 The theme name.
# ---
function updateWaybar() {
    command -v waybar > /dev/null 2>&1 || return

    echo -en "  Changing waybar theme......................."

    [ -f $HOME/.config/waybar ] && rm $HOME/.config/waybar

    if [[ ! -d $DIR/themes/$1/waybar ]]; then
        echo -e "\E[1;33mSKIP\033[0m"
        return
    fi

    mkdir -p $HOME/.config/waybar
    envsubst < $DIR/themes/$1/waybar/config > $HOME/.config/waybar/config
    envsubst < $DIR/themes/$1/waybar/style.css > $HOME/.config/waybar/style.css

    killall waybar > /dev/null 2>&1


    waybar > /dev/null 2>&1 &

    echo -e "\E[1;32mDONE\033[0m"
}

# ---
# Changes the zsh theme.
#
# @param $1 The theme name.
# ---
function updateZsh() {
    command -v zsh > /dev/null 2>&1 || return

    echo -en "  Changing zsh theme.........................."

    [ -f $HOME/.config/zsh/config/environments/theme.sh ] && rm $HOME/.config/zsh/config/environments/theme.sh

    if [[ ! -f $DIR/themes/$1/zsh/theme.sh ]]; then
        echo -e "\E[1;33mSKIP\033[0m"
        return
    fi

    mkdir -p $HOME/.config/zsh/config/environments
    cp $DIR/themes/$1/zsh/theme.sh $HOME/.config/zsh/config/environments/theme.sh

    echo -e "\E[1;32mDONE\033[0m"
}

# ---
# Changes the yazi theme.
#
# @param $1 The theme name.
# ---
function updateYazi() {
    command -v yazi > /dev/null 2>&1 || return

    echo -en "  Changing yazi theme........................."

    [ -f $HOME/.config/yazi ] && rm $HOME/.config/yazi

    if [[ ! -d $DIR/themes/$1/yazi ]]; then
        echo -e "\E[1;33mSKIP\033[0m"
        return
    fi

    mkdir -p $HOME/.config/yazi
    envsubst < $DIR/themes/$1/yazi/theme.toml > $HOME/.config/yazi/theme.toml

    echo -e "\E[1;32mDONE\033[0m"
}

main "$@"
