#!/bin/sh

bspc config border_width         3
bspc config normal_border_color  \$future_bg_mt
bspc config active_border_color  \$future_bg_mt
bspc config focused_border_color \$future_bg_hl
bspc config window_gap           20
#17BEBB
