#!/bin/sh

bspc config border_width         3
bspc config normal_border_color  \$future_mt_bg
bspc config active_border_color  \$future_mt_bg
bspc config focused_border_color \$future_hl_bg
bspc config window_gap           20
#17BEBB
