#!/bin/sh

bspc config border_width         1
bspc config normal_border_color  \#20202a
bspc config active_border_color  \#20202a
bspc config focused_border_color \#ff79c6
bspc config window_gap           26
