#!/bin/sh

bspc config border_width         3
bspc config normal_border_color  \$air_bg
bspc config active_border_color  \$air_bg
bspc config focused_border_color \$air_hl
bspc config window_gap           20
