#!/bin/sh

bspc config border_width         5
bspc config normal_border_color  \$color16
bspc config active_border_color  \$color16
bspc config focused_border_color \$color17
bspc config window_gap           30
