#!/bin/sh

bspc config border_width         5
bspc config normal_border_color  \$flat_nm_bg
bspc config active_border_color  \$flat_nm_bg
bspc config focused_border_color \$flat_mt_fg
bspc config window_gap           30
